openapi: 3.1.0
info:
  title: GitHub Profile Readme PostProcessor
  description: A tool that leverages GitHub's built-in features to automatically update your GitHub profile readme file based on your situation and display needs, making the resume of your open-source journey on GitHub more direct, pure, and clear.
  version: 0.9.0

servers:
  - url: '/v1'

paths:
  /support/markdown:
    $ref: './paths/support/markdown.yaml'

  /contributed-repositories:
    $ref: './paths/contributed-repositories/endpoint.yaml'

  /contributed-repositories/markdown:
    $ref: './paths/contributed-repositories/markdown.yaml'
